site_name: RATHNA SCHOOLS

nav:
    - Python Introduction: index.md
    - Python Data Types: python_data_types.md
    - Python Comments: python_comments.md
    - Python Variables: python_variables.md
    - Python Operators: python_operators.md
    - Python Numbers: python_numbers.md
    - Python Strings: python_strings.md
    - String Functions: string_functions.md
    - Python Lists: python_lists.md
    - List Functions: list_functions.md
    - Python Tuples: python_tuples.md
    - Tuple Functions: tuple_functions.md
    - Python Sets: python_sets.md
    - Set Functions: set_functions.md
    - Python Dictionary: python_dictionary.md
    - Dict Functions: dict_functions.md
    - Python Keywords: python_keywords.md
    - Conditional Statement: conditional_statement.md
    - While Loop Statements: while_loop.md
    - For Loop Statements: for_loop.md
    - User Defined Functions: user_defined_function.md
    - Function Arguments: function_arguments.md
    - Special Parameters: special_parameters.md  
    - Lambda Functions: lambda_functions.md  
    - Inbuilt Functions: inbuilt_functions.md  
    
theme:
  name: material  