site_name: RATHNA SCHOOLS

nav:
    - Python Introduction: index.md
    - Python Data Types: python_data_types.md
    - Python Comments: python_comments.md
    - Python Variables: python_variables.md
    - Python Operators: python_operators.md
    - Python Numbers: python_numbers.md
    - Python Strings: python_strings.md
    - String Functions: string_functions.md

theme:
  name: material  